# Generated by Django 2.2.1 on 2021-02-20 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210220_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 20, 14, 10, 54, 813767)),
        ),
        migrations.AddField(
            model_name='user',
            name='fruit',
            field=models.ManyToManyField(to='api.Fruit'),
        ),
        migrations.AddField(
            model_name='user',
            name='vegetables',
            field=models.ManyToManyField(to='api.Vegetable'),
        ),
    ]
