# Generated by Django 2.2.1 on 2021-02-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210220_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registered',
            field=models.DateTimeField(blank=True, default='2016-07-13T12:29:07 -10:00'),
        ),
    ]
