# Generated by Django 2.2.1 on 2021-02-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210225_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='favouriteFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='favouriteFood',
            field=models.ManyToManyField(blank=True, to='api.favouriteFood'),
        ),
    ]
