# Generated by Django 2.2.1 on 2021-02-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210228_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, related_name='employees', to='api.Company'),
        ),
    ]
