# Generated by Django 2.2.1 on 2021-03-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210228_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='employees', to='api.Company'),
        ),
    ]
